### PR TITLE
Updated prismjs version

### PR DESCRIPTION
**Pull request by felipeleusin**
This is to add support to new languages like tsx. Tests pass and nothing seems to be broken on storybook.

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@kitten -- Have we gotten around that "you can't ever have 2+ different versions of `prismjs` thing or else world breaks" issue?

If not, and if we want this change, we'll have to group up and batch release all the Formidable projects that depend on this one and use a separate `prismjs`

**Comment by felipeleusin** [comment]
Yeah. I was considering suggesting moving prismjs to a peerDependency for  react-live. probably prismjs >= 1.6 && <2 or something

**Comment by tujoworker** [comment]
Yeah, would love to have this in! Who is making a release?

**Comment by felipeleusin** [comment]
Is there any way I can help get this going?

**Pull request closed without merging**
