### PR TITLE
Replace tab-indentation with 2 whitespaces

### LINKED ISSUE #37: Tab normalization breaks Safari
We are seeing broken indentation in Safari:

screen shot 2017-09-27 at 8 07 21 pm

This happens because [normalization replaces spaces with tabs](https://github.com/FormidableLabs/react-live/blob/ed390f5ea5a084c3e2d447147d619ec0c9d10108/src/utils/normalizeCode.js#L3).

For now we'll fork and fix the normalization to use spaces, but I hope this can be solved upstream :-)

### PR DESCRIPTION
**Pull request by philpl**
Fix #37

### CODE REVIEW

**Comment by gaearon** [comment]
Can you publish it to a canary so we can try this on reactjs.org?

**Comment by philpl** [comment]
@gaearon sure, I’ll publish a minor prerelease

**Comment by gaearon** [comment]
Hey Ken

**Comment by philpl** [comment]
@gaearon Alright, you should be able to use 1.8.0-0 published on react-live@next

**Comment by kenwheeler** [comment]
Hi DANNNNNN

**Pull request merged**
