### PR TITLE
TypeScript typings: expose `theme` prop

### PR DESCRIPTION
**Pull request by benmosher**
I am currently working around with `// @ts-ignore` but would be nicer to specify the `theme` without that.

Added `type Theme = any`, not sure exactly what the type should be.

### CODE REVIEW

**Comment by hasparus** [comment]
https://github.com/FormidableLabs/react-live/pull/135

**Comment by hasparus** [comment]
I had the same problem @benmosher :D

**Comment by sofiapoh** [comment]
If I'm not completely wrong I think we should be using [this type](https://github.com/FormidableLabs/prism-react-renderer/blob/master/index.d.ts#L87) as the theme comes from `prism-react-renderer` cc @kitten

**Comment by benmosher** [comment]
#135 is better 👍🏼

**Pull request closed without merging**
