### PR TITLE
wip: Use react-simple-code-editor instead of contentEditable

### PR DESCRIPTION
**Pull request by satya164**
The PR replaces the default editor implementation with http://satya164.xyz/react-simple-code-editor/

react-simple-code-editor is much simpler due to it merely being a `textarea`. It also has better indentation behavior (you can both indent and unindent blocks of selected code), and implements a shortcut to toggle tab trapping similar to Monaco editor.

I was unable to run the next js website which crashes for me due out of memory issue. Any help regarding that will be awesome.

cc @kitten

### CODE REVIEW

**Comment by jquense** [comment]
very coool!

**Comment by JReinhold** [comment]
How's this coming along? I could use this upgrade, since I'm having some difficulties with the Editor reacting to onKeyUp events, and I see that those are deleted here. If there's anything I can help with, please let me know!

💪

**Comment by satya164** [comment]
cc @sofiapoh

**Comment by kitten** [comment]
Merged via v2

**Pull request closed without merging**
